version: '3.1'

services:
  db:
    image: postgres:13.7-alpine
    restart: always
    environment:
      POSTGRES_DB: 'movie_library'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '@morim2014'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/movie_library

volumes:
  db:
